/* Generated by scripts/verdict-to-episode.mjs — do not edit by hand. */
window.EXPLAINER = (function () {
  const ex = window.CetiExplainer;
  const { ramp, seg, fit, ease } = ex;
  const flags = { math: true };
const DATA = {"title":"Cellular sheaves — paper stalks","pillars":[{"id":"paper","folder":"paper"},{"id":"sections","folder":"sections"},{"id":"rho","folder":"restriction"},{"id":"delta","folder":"coboundary"},{"id":"laplace","folder":"laplacian"},{"id":"harmonic","folder":"harmonic"}],"maps":[{"id":"r-ps","from":"paper","to":"sections","status":"ok"},{"id":"r-pr","from":"paper","to":"restriction","status":"ok"},{"id":"r-pd","from":"paper","to":"coboundary","status":"ok"},{"id":"r-pl","from":"paper","to":"laplacian","status":"strange"},{"id":"r-sd","from":"sections","to":"coboundary","status":"ok"},{"id":"r-rd","from":"restriction","to":"coboundary","status":"ok"},{"id":"r-dl","from":"coboundary","to":"laplacian","status":"ok"},{"id":"r-lh","from":"laplacian","to":"harmonic","status":"missing"}],"verdict":"Fix laplacian → harmonic and the trunk closes.","repairs":[{"label":"laplacian → harmonic · closes the trunk","opens":["harmonic"],"closesTrunk":true,"line":"This one map closes the trunk. No harmonic extension written. Cobb–Gebhart needs this ρ."},{"label":"paper → laplacian · opens nothing","opens":[],"closesTrunk":false,"line":"Opens no new folder. harmonic still closed. Δ_F = δᵀδ. Rank of the spectrum is odd until harmonic is written."}]};
  const beats = [
  {
    "id": "b1",
    "label": "The folders",
    "dur": 3.8,
    "caption": "6 stalk folders — the vertices of the sheaf graph."
  },
  {
    "id": "b2",
    "label": "The maps",
    "dur": 5.2,
    "caption": "8 restriction maps between folders, coloured by glue status."
  },
  {
    "id": "b3",
    "label": "What blocks",
    "dur": 4.6,
    "caption": "Non-ok maps are the blockers; count them before picking a fix."
  },
  {
    "id": "b4",
    "label": "Repair #1",
    "dur": 5.4,
    "caption": "This one map closes the trunk. No harmonic extension written. Cobb–Gebhart needs this ρ."
  },
  {
    "id": "b5",
    "label": "Repair #2",
    "dur": 5,
    "caption": "Opens no new folder. harmonic still closed. Δ_F = δᵀδ. Rank of the spectrum is odd until harmonic is written."
  },
  {
    "id": "b6",
    "label": "How we rank",
    "dur": 5,
    "caption": "Order: closes trunk first, then opens more folders, then status, then residual."
  },
  {
    "id": "b7",
    "label": "The verdict",
    "dur": 4.8,
    "caption": "Fix laplacian → harmonic and the trunk closes."
  },
  {
    "id": "why",
    "label": "Why it matters",
    "dur": 5.8,
    "caption": "One map ranks first — fixing it is the cheapest counterfactual way to fold more folders."
  }
];

  const VW = 1000, VH = 464;
  const ACC = "var(--ex-accent)", ACC2 = "var(--ex-accent2)", SUP = "var(--ex-support)";
  const INK = "var(--ex-ink)", DIM = "var(--ex-dim)", LINE = "var(--ex-line)";
  const PANEL = "var(--ex-panel)", CELL = "var(--ex-cell)";
  const LT_Y = 302;
  const statusColor = (s) =>
    s === "ok" ? SUP : s === "strange" ? ACC2 : ACC;

  const NS = "http://www.w3.org/2000/svg";
  function el(tag, attrs, parent) {
    const n = document.createElementNS(NS, tag);
    if (attrs)
      for (const k in attrs)
        k === "text" ? (n.textContent = attrs[k]) : n.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(n);
    return n;
  }
  const g = (p, a) => el("g", a, p);
  const setO = (n, o) => { n.style.opacity = o; };

  const D = {};
  const nP = DATA.pillars.length;
  const chipY = 56, chipH = 32, chipPad = 8;
  const xAt = (i) => (nP <= 1 ? VW / 2 : 70 + (i * (VW - 140)) / (nP - 1));
  const folderIx = (name) => DATA.pillars.findIndex((p) => p.folder === name);

  function auditCounts() {
    const maps = DATA.maps || [];
    const nonOk = maps.filter((m) => m.status !== "ok").length;
    const by = { ok: 0, strange: 0, broken: 0, missing: 0 };
    for (const m of maps) by[m.status] = (by[m.status] || 0) + 1;
    return { nonOk, by };
  }

  function build(stage, opts) {
    D.beats = {};
    opts.beats.forEach((b) => (D.beats[b.id] = b));
    const svg = el(
      "svg",
      {
        viewBox: "0 0 " + VW + " " + VH,
        width: "100%",
        height: "100%",
        "font-family": "var(--font-sans)",
        role: "img",
        "aria-label": DATA.title + " sheaf verdict",
      },
      stage,
    );
    D.svg = svg;

    D.ltRule = el("line", { x1: 44, y1: LT_Y, x2: VW - 44, y2: LT_Y, stroke: LINE, "stroke-width": 1 }, svg);
    setO(D.ltRule, 0);

    D.anchor = g(svg);
    D.mapsLayer = g(svg);
    D.workLayer = g(svg, { transform: "translate(0 132)" });
    D.detailLayer = g(svg, { transform: "translate(0 " + (LT_Y + 12) + ")" });

    D.chips = DATA.pillars.map((p, i) => {
      const x = xAt(i);
      const grp = g(D.anchor, { transform: "translate(" + x + " " + chipY + ")" });
      const w = Math.min(118, Math.max(72, p.folder.length * 7 + 24));
      el("rect", {
        x: -w / 2, y: 0, width: w, height: chipH, rx: 6,
        fill: PANEL, stroke: LINE, "stroke-width": 1,
      }, grp);
      const tx = el("text", {
        x: 0, y: chipH / 2 + 1, "text-anchor": "middle", "dominant-baseline": "middle",
        "font-family": "var(--font-sans)", "font-size": 13, fill: INK, text: p.folder,
      }, grp);
      fit(tx, w - chipPad);
      setO(grp, 0);
      return { grp, x, w, folder: p.folder };
    });

    D.mapSegs = DATA.maps.map((m) => {
      const fi = folderIx(m.from), ti = folderIx(m.to);
      const path = el("line", {
        x1: xAt(fi), y1: chipY + chipH + 4,
        x2: xAt(ti), y2: chipY + chipH + 4,
        stroke: statusColor(m.status), "stroke-width": 2, "stroke-linecap": "round",
      }, D.mapsLayer);
      setO(path, 0);
      const tag = el("text", {
        x: (xAt(fi) + xAt(ti)) / 2, y: chipY + chipH + 18,
        "text-anchor": "middle", "font-family": "var(--font-mono)", "font-size": 11,
        fill: statusColor(m.status), text: m.status,
      }, D.mapsLayer);
      setO(tag, 0);
      return { path, tag };
    });

    const ac = auditCounts();
    D.auditShown = ac;

    D.sBlock = g(D.workLayer);
    el("text", { x: VW / 2, y: 24, "text-anchor": "middle", "font-size": 13, fill: DIM,
      text: "Non-ok restriction maps" }, D.sBlock);
    D.blockNum = el("text", { x: VW / 2, y: 72, "text-anchor": "middle",
      "font-family": "var(--font-mono)", "font-size": 42, fill: ACC, text: String(ac.nonOk) }, D.sBlock);
    D.statusRow = g(D.sBlock, { transform: "translate(" + (VW / 2 - 180) + " 104)" });
    ["strange", "broken", "missing", "ok"].forEach((st, i) => {
      const col = g(D.statusRow, { transform: "translate(" + (i * 95) + " 0)" });
      el("text", { x: 0, y: 0, "font-family": "var(--font-mono)", "font-size": 11, fill: DIM, text: st }, col);
      el("text", { x: 0, y: 22, "font-family": "var(--font-mono)", "font-size": 16,
        fill: statusColor(st), text: String(ac.by[st] || 0) }, col);
    });
    setO(D.sBlock, 0);

    function repairScene(parent, repair, fallbackTitle) {
      const sc = g(parent);
      const title = repair ? repair.label : fallbackTitle;
      const body = repair ? repair.line : "No ranked repair — graph may already fold.";
      const t1 = el("text", { x: 60, y: 28, "font-family": "var(--font-mono)", "font-size": 12,
        fill: ACC, text: title }, sc);
      fit(t1, VW - 120);
      const t2 = el("text", { x: 60, y: 58, "font-size": 13, fill: INK, text: body }, sc);
      fit(t2, VW - 120);
      if (repair) {
        el("text", { x: 60, y: 96, "font-size": 12, fill: DIM,
          text: repair.closesTrunk ? "Closes the trunk if flipped to ok." :
            (repair.opens.length ? "Opens: " + repair.opens.join(", ") : "Opens no new folder.") }, sc);
      }
      setO(sc, 0);
      return sc;
    }

    D.sR1 = repairScene(D.workLayer, DATA.repairs[0], "Repair queue empty");
    D.sR2 = repairScene(
      D.workLayer,
      DATA.repairs[1],
      DATA.repairs[0] ? DATA.repairs[0].line : "Residual folders",
    );
    D.sR3 = repairScene(
      D.workLayer,
      DATA.repairs[2],
      "Ranking: closes trunk, then opens more, then status, then residual.",
    );

    D.sVerdict = g(D.workLayer);
    el("text", { x: 60, y: 28, "font-family": "var(--font-mono)", "font-size": 11,
      "letter-spacing": "0.16em", fill: DIM, text: "VERDICT" }, D.sVerdict);
    D.verdictText = el("text", { x: 60, y: 62, "font-size": 16, fill: INK, text: DATA.verdict }, D.sVerdict);
    fit(D.verdictText, VW - 120);
    setO(D.sVerdict, 0);

    D.sWhy = g(D.detailLayer);
    el("text", { x: 60, y: 20, "font-family": "var(--font-mono)", "font-size": 11,
      fill: DIM, text: "CHEAPEST COUNTERFACTUAL" }, D.sWhy);
    const whyLead = DATA.repairs[0]
      ? "Flip " + DATA.repairs[0].label + " first — it wins the ranking."
      : "Every map already commutes.";
    el("text", { x: 60, y: 48, "font-size": 14, fill: INK, text: whyLead }, D.sWhy);
    el("text", { x: 60, y: 78, "font-size": 13, fill: DIM,
      text: "Audits end in a film when the graph verdict must land with a team." }, D.sWhy);
    setO(D.sWhy, 0);

    [D.sBlock, D.sR1, D.sR2, D.sR3, D.sVerdict, D.sWhy].forEach((s) => setO(s, 0));
  }

  function render(t) {
    const B = D.beats;
    const mathOn = flags.math ? 1 : 0;

    DATA.pillars.forEach((_, i) => {
      const a = ramp(t, B.b1.start + 0.12 + i * 0.1, 0.45, ease.defer);
      setO(D.chips[i].grp, a);
    });

    const mapOn = seg(t, B.b2.start + 0.2, B.b3.start, 0.35);
    D.mapSegs.forEach((seg, i) => {
      const a = mapOn * ramp(t, B.b2.start + 0.15 + i * 0.06, 0.4);
      setO(seg.path, Math.max(a, 0.12));
      setO(seg.tag, a);
    });

    setO(D.sBlock, seg(t, B.b3.start + 0.2, B.b4.start, 0.35));
    setO(D.sR1, seg(t, B.b4.start + 0.2, B.b5.start, 0.35));
    setO(D.sR2, seg(t, B.b5.start + 0.2, B.b6.start, 0.35));
    setO(D.sR3, seg(t, B.b6.start + 0.2, B.b7.start, 0.35));
    setO(D.sVerdict, seg(t, B.b7.start + 0.2, B.why.start, 0.35));
    setO(D.sWhy, seg(t, B.why.start + 0.2, B.why.end + 0.5, 0.35) * mathOn);
    setO(D.ltRule, ramp(t, B.b3.start, 0.5) * mathOn);
  }

  window.__AUDIT = function () {
    const want = auditCounts();
    const shown = D.auditShown || want;
    if (shown.nonOk !== want.nonOk) {
      return { ok: false, msg: "non-ok count mismatch" };
    }
    for (const k of ["ok", "strange", "broken", "missing"]) {
      if ((shown.by[k] || 0) !== (want.by[k] || 0)) {
        return { ok: false, msg: "status count mismatch for " + k };
      }
    }
    return { ok: true, note: "blocker counts match DATA.maps" };
  };

  window.__REGIONS = function () {
    return {
      working: [D.sBlock, D.sR1, D.sR2, D.sR3, D.sVerdict],
      detail: [D.sWhy],
    };
  };

  window.__LAYOUT = function () {
    return [D.anchor, D.mapsLayer, D.sBlock, D.sR1, D.sR2, D.sR3, D.sVerdict, D.sWhy];
  };

  return {
    meta: {
      id: "paper-trunk-verdict",
      eyebrow: "SHEAF · VERDICT",
      title: DATA.title,
      lede: "A sheaf graph audit rendered as an eight-beat explainer — folders, maps, ranked repairs.",
      synthTitle: "What the <em>ranking</em> says",
      tag: DATA.pillars.length + " folders · " + DATA.maps.length + " maps",
      synthesis:
        "Glue status on each restriction map drives a repair ranking; the verdict names the single cheapest flip that opens more of the trunk.",
    },
    beats,
    build,
    render,
    setMath(on) { flags.math = !!on; },
  };
})();
